/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package be.ipam.spotify.api;

import be.ipam.spotify.api.model.Album;
import java.math.BigDecimal;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.CookieValue;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;

@Validated
@Api(value = "Album", description = "the Album API")
public interface AlbumApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /api/v1/albums : Create the album
     * Create the album
     *
     * @param album album object (optional)
     * @return created (status code 201)
     */
    @ApiOperation(value = "Create the album", nickname = "createAlbum", notes = "Create the album", tags={ "album", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "created") })
    @RequestMapping(value = "/api/v1/albums",
        consumes = { "application/xml", "application/json" },
        method = RequestMethod.POST)
    default ResponseEntity<Void> createAlbum(@ApiParam(value = "album object"  )  @Valid @RequestBody(required = false) Album album) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * DELETE /api/v1/album/{albumId} : Delete the artist
     * Deletes the song
     *
     * @param albumId album id (required)
     * @return successful operation (status code 204)
     *         or Given album ID doesn&#39;t exist (status code 404)
     */
    @ApiOperation(value = "Delete the artist", nickname = "deleteAlbum", notes = "Deletes the song", tags={ "album", })
    @ApiResponses(value = { 
        @ApiResponse(code = 204, message = "successful operation"),
        @ApiResponse(code = 404, message = "Given album ID doesn't exist") })
    @RequestMapping(value = "/api/v1/album/{albumId}",
        method = RequestMethod.DELETE)
    default ResponseEntity<Void> deleteAlbum(@ApiParam(value = "album id",required=true) @PathVariable("albumId") BigDecimal albumId) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /api/v1/album/{albumId} : Returns the album
     * Returns the album
     *
     * @param albumId Album Identifier (required)
     * @return successful operation (status code 200)
     *         or Given album ID doesn&#39;t exist (status code 404)
     */
    @ApiOperation(value = "Returns the album", nickname = "getAlbumById", notes = "Returns the album", tags={ "album", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation"),
        @ApiResponse(code = 404, message = "Given album ID doesn't exist") })
    @RequestMapping(value = "/api/v1/album/{albumId}",
        method = RequestMethod.GET)
    default ResponseEntity<Void> getAlbumById(@ApiParam(value = "Album Identifier",required=true) @PathVariable("albumId") Integer albumId) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /api/v1/album/{albumId} : Update the album
     * Update the album
     *
     * @param albumId album id (required)
     * @param album album object (optional)
     * @return updated (status code 200)
     */
    @ApiOperation(value = "Update the album", nickname = "updateAlbum", notes = "Update the album", tags={ "album", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "updated") })
    @RequestMapping(value = "/api/v1/album/{albumId}",
        consumes = { "application/xml", "application/json" },
        method = RequestMethod.PUT)
    default ResponseEntity<Void> updateAlbum(@ApiParam(value = "album id",required=true) @PathVariable("albumId") BigDecimal albumId,@ApiParam(value = "album object"  )  @Valid @RequestBody(required = false) Album album) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
