/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package be.ipam.spotify.api;

import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.CookieValue;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import be.ipam.spotify.api.model.Artist;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;

@Validated
@Api(value = "Artist", description = "the Artist API")
public interface ArtistApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /api/v1/artists/{artistId} : Returns the artist
     * Returns the artist
     *
     * @param artistId Artist Identifier (required)
     * @return successful operation (status code 200)
     *         or Given song ID doesn&#39;t exist (status code 404)
     */
    @ApiOperation(value = "Returns the artist", nickname = "getArtistById", notes = "Returns the artist", tags={ "artist", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation"),
        @ApiResponse(code = 404, message = "Given song ID doesn't exist") })
    @RequestMapping(value = "/api/v1/artists/{artistId}",
        method = RequestMethod.GET)
    default ResponseEntity<Artist> getArtistById(@ApiParam(value = "Artist Identifier",required=true) @PathVariable("artistId") Long artistId) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
