/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package be.ipam.spotify.api;

import java.math.BigDecimal;
import be.ipam.spotify.api.model.Playlist;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.CookieValue;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;

@Validated
@Api(value = "Playlist", description = "the Playlist API")
public interface PlaylistApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /api/v1/playlists : Create the playlist
     * Create the playlist
     *
     * @param playlist playylist object (optional)
     * @return created (status code 201)
     */
    @ApiOperation(value = "Create the playlist", nickname = "createPlaylist", notes = "Create the playlist", tags={ "playlist", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "created") })
    @RequestMapping(value = "/api/v1/playlists",
        consumes = { "application/xml", "application/json" },
        method = RequestMethod.POST)
    default ResponseEntity<Void> createPlaylist(@ApiParam(value = "playylist object"  )  @Valid @RequestBody(required = false) Playlist playlist) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * DELETE /api/v1/playlists/{playlistId} : Delete the playlist
     * Deletes the playlist
     *
     * @param playlistId album id (required)
     * @return successful operation (status code 204)
     *         or Given album ID doesn&#39;t exist (status code 404)
     */
    @ApiOperation(value = "Delete the playlist", nickname = "deletePlaylist", notes = "Deletes the playlist", tags={ "playlist", })
    @ApiResponses(value = { 
        @ApiResponse(code = 204, message = "successful operation"),
        @ApiResponse(code = 404, message = "Given album ID doesn't exist") })
    @RequestMapping(value = "/api/v1/playlists/{playlistId}",
        method = RequestMethod.DELETE)
    default ResponseEntity<Void> deletePlaylist(@ApiParam(value = "album id",required=true) @PathVariable("playlistId") BigDecimal playlistId) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /api/v1/playlists/{playlistId} : Returns the playlist
     * Returns the playlist
     *
     * @param playlistId Playlist Identifier (required)
     * @return successful operation (status code 200)
     *         or Given playlist ID doesn&#39;t exist (status code 404)
     */
    @ApiOperation(value = "Returns the playlist", nickname = "getPlaylistById", notes = "Returns the playlist", tags={ "playlist", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation"),
        @ApiResponse(code = 404, message = "Given playlist ID doesn't exist") })
    @RequestMapping(value = "/api/v1/playlists/{playlistId}",
        method = RequestMethod.GET)
    default ResponseEntity<Void> getPlaylistById(@ApiParam(value = "Playlist Identifier",required=true) @PathVariable("playlistId") Integer playlistId) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /api/v1/playlists/{playlistId} : Update the playlist
     * Update the playlist
     *
     * @param playlistId playlist id (required)
     * @param playlist playlist object (optional)
     * @return updated (status code 200)
     */
    @ApiOperation(value = "Update the playlist", nickname = "updatePlaylist", notes = "Update the playlist", tags={ "playlist", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "updated") })
    @RequestMapping(value = "/api/v1/playlists/{playlistId}",
        consumes = { "application/xml", "application/json" },
        method = RequestMethod.PUT)
    default ResponseEntity<Void> updatePlaylist(@ApiParam(value = "playlist id",required=true) @PathVariable("playlistId") BigDecimal playlistId,@ApiParam(value = "playlist object"  )  @Valid @RequestBody(required = false) Playlist playlist) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
